import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'
import Header from './component/Header'
import Wrap from './component/Wrap'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Ecommers website',
  description: 'Generated by create next app'
}        
 
export default function RootLayout({ children }){
  return (
    <html lang="en">
    <Head>
    <link rel="icon" href="logo.png" />
   </Head>    
     <body suppressHydrationWarning={true} className={inter.className}>
     <Wrap>
     <Header/>
      {children}
     </Wrap>
       </body>
    </html>
  )
}